### ISSUE TITLE
TS2345 in a fresh ember app

### ISSUE THREAD

**Issue by ro0gr** [cibernox/ember-power-select#1601]
Hey 👋 I've just noticed in a fresh ember typescript app with the latest(`7.1.2`) ember-power-select installed, I have the following TS error:

```sh
npm run lint:types 

> ln-ember-form@0.0.0 lint:types
> tsc --noEmit

../../node_modules/ember-power-select/addon/components/power-select.ts:148:35 - error TS2345: Argument of type 'IArguments' is not assignable to parameter of type '[]'.

148     super.willDestroy.apply(this, arguments);
                                      ~~~~~~~~~


Found 1 error in ../../node_modules/ember-power-select/addon/components/power-select.ts:148
```

This comes from the https://github.com/cibernox/ember-power-select/blob/ae707d0e4a0baf8477d2629a51a27cee00753648/addon/components/power-select.ts#L148, which has been introduced in https://github.com/cibernox/ember-power-select/pull/1392/commits/637354e054c44a06e08bdfc58d432d96bbc43937#diff-3a81f677e664ccdc7a0222ae6e84cdb47839fea70fcc92e6db2ad93a7d912badR141 and seems to be an accidental `arguments` usage here.

AFAIK, glimmer component `willDestroy` does not accept any arguments, so I believe we should be safe just to remove the invocation arguments. Thanks!
