### ISSUE TITLE
`selectChoose` does not work with PhantomJS and Ember 2.4.5

### ISSUE THREAD

**Issue by Mr-TaylorHobbs** [cibernox/ember-power-select#604]
Using Ember 2.4.5, CLI 2.6.3, and Data 2.7.0 with power select 0.10.10.

I cannot use `selectChoose` in my tests with PhantomJS, it works in the browser however. In Phantom I receive the following error
```TypeError: 'undefined' is not a function (evaluating 'this._touchMoveHandler.bind(this)')```

**Comment by cibernox** [comment]
I suspect that you are using phantom 1.9.X which dates from 2014. 
The readme warns that this addon requires phantom 2.0 or bigger [see here](https://github.com/cibernox/ember-power-select#testing)

Is that the case?

**Comment by Mr-TaylorHobbs** [comment]
@cibernox That was it. Thank you.
