### ISSUE TITLE
Uncaught TypeError: keyword is not a function

### ISSUE THREAD

**Issue by Vasleo** [cibernox/ember-power-select#687]
Am trying to use power select inside of a component in my custom Addon, and I see the below error.,

**Uncaught TypeError: keyword is not a function**

The piece of code that has this error is below.,

    _var keyword = env.hooks.keywords[helperName];
    if (keyword) {
      return keyword(null, env, scope, params, hash, null, null);
    }_

But when I try to run the same code as just an app, it works.
Am trying to replicate what was the first select example @ http://www.ember-power-select.com/docs/how-to-use-it

And when I try to debug, the above mentioned code errors out when the value of helperName is component.

FYI-
DEBUG: -------------------------------
DEBUG: Ember      : 2.0.0
DEBUG: Ember Data : 1.13.15
DEBUG: jQuery     : 1.11.3
DEBUG: ------------------------------- 

Am not sure what the issue is.

**Comment by cibernox** [comment]
This component requires Ember 2.4 or bigger. I think that it works with 2.3.1 too, but not older. Check with a newer version of ember and if the problem persists feel free to reopen.
